### ISSUE TITLE
关于reducer问题

### ISSUE THREAD

**Issue by shen-lan** [mafeifan/react-dianping#1]
你好。打扰了。
本人新手刚学习react
看了楼主的代码，shop.js这个reducer。
其中， 
```
   case actionTypes.SHOP_ADD:
      state.unshift(action.data)
      return state
```
看官方资料，reducer要求是纯函数，不能修改state，
这处代码没问题吗？

**Comment by mafeifan** [comment]
不好意思，我现在工作上不接触了react了。当时怎么写的忘记了。
你说的应该没错，应该是我的写法问题

**Comment by shen-lan** [comment]
没关系 ，我再看下其他的资料。谢谢你的回答
